// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_Hwji6VJDTNaII5msVXUckSqhKzFDm_M',
    appId: '1:1076314162527:web:7aea75befde08b264322ea',
    messagingSenderId: '1076314162527',
    projectId: 'trosy-app',
    authDomain: 'trosy-app.firebaseapp.com',
    storageBucket: 'trosy-app.firebasestorage.app',
    measurementId: 'G-L1QWB1C49X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwPe83zdcWxHIkOyt5ECWFIzMWA913ims',
    appId: '1:1076314162527:android:310b9f28a35158924322ea',
    messagingSenderId: '1076314162527',
    projectId: 'trosy-app',
    storageBucket: 'trosy-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMuWasM7pSkHs2fmvA6l-5ifVRaZC-fC0',
    appId: '1:1076314162527:ios:6ec784fa7c8d6d594322ea',
    messagingSenderId: '1076314162527',
    projectId: 'trosy-app',
    storageBucket: 'trosy-app.firebasestorage.app',
    iosBundleId: 'com.example.trosyDriver',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMuWasM7pSkHs2fmvA6l-5ifVRaZC-fC0',
    appId: '1:1076314162527:ios:6ec784fa7c8d6d594322ea',
    messagingSenderId: '1076314162527',
    projectId: 'trosy-app',
    storageBucket: 'trosy-app.firebasestorage.app',
    iosBundleId: 'com.example.trosyDriver',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_Hwji6VJDTNaII5msVXUckSqhKzFDm_M',
    appId: '1:1076314162527:web:7441660fc362c93b4322ea',
    messagingSenderId: '1076314162527',
    projectId: 'trosy-app',
    authDomain: 'trosy-app.firebaseapp.com',
    storageBucket: 'trosy-app.firebasestorage.app',
    measurementId: 'G-822QDMM1V9',
  );

}